### ISSUE TITLE
Improvements to the certificates

### ISSUE THREAD

**Issue by Shagon94** [kchristensen/udm-le#100]
Looking at the script:

https://github.com/kchristensen/udm-le/blob/b5959d3d12643a2f6bee77ed68b6e52b1b012a96/udm-le.sh#L215-L216

The script renews the certificate every 30 days. The default value for `--days` is 30, meaning when the certificate has less than 30 days it will renew it. It is unnecessary to renew it every 30 days, and either removing the `--days` option, or having it be a configurable value is a better solution, for example having it as an environment variable in the `udm-le.env` file.

In terms of having the renewal attempt every day via the timer and the service - that too should be configurable, or a better sane default set.

If we renew every 60 days (30 days before it expires) we can check every week instead of every day. An area of improvement is having this configurable as well.

**Comment by Shagon94** [comment]
https://github.com/kchristensen/udm-le/pull/101 is created to allow for this functionality.

In terms of changing the service - that's something that doesn't seem to be "easily" customizable, unless you manually change the service files before running the tool

**Comment by kchristensen** [comment]
Thanks for the PR! I'm not going to sweat changing the service -- the nightly check to see if a certificate is valid is something most places using Let's Encrypt are doing and they're equipped to handle the traffic, so I'd rather not get in a scenario where people are able to misconfigure the values and get themselves into a situation where their certificates expire.

**Comment by Shagon94** [comment]
closed with #101
