### ISSUE TITLE
Can't apply certificate to captive portal - No java

### ISSUE THREAD

**Issue by mrk3767** [kchristensen/udm-le#102]
In the current version of firmware for my UDM, the java binary doesn't exist. I did a search for it and it doesn't look like it's anywhere on disk unless I missed it.

```
root@Daiya:/data/udm-le# java
-bash: java: command not found
```

https://github.com/kchristensen/udm-le/blob/3e91eaeb4fdb7d9368c8ce7db97a52b7a284df84/udm-le.env#L140C18-L140C70

**Comment by mrk3767** [comment]
I was able to add the certs using KeyStore Explorer (Windows app). I went to Tools > Add Import Key Pair. I selected both files and set the password on the imported pair. I then renamed it to unifi and uploaded it back to the controller.

**Comment by kchristensen** [comment]
What version are you running? I'm on 4.1.5 on my UDW, and things seem to be working fine (java is `/usr/bin/java`).

**Comment by mrk3767** [comment]
UniFi OS v4.0.20
Network 8.5.6

```
Linux Daiya 4.19.152-ui-alpine #4.19.152 SMP Thu Sep 12 13:20:59 CST 2024 aarch64

root@Daiya:~# ls /usr/bin/ | grep java
root@Daiya:~#
```

**Comment by kchristensen** [comment]
Anyone else on v4.0.20 that can confirm? My udw is on v4.1.5 and it's still there, and I checked a udmse on v4.0.6 that also has it at `/usr/bin/java`.

**Comment by mgd43b** [comment]
I'm on 4.0.21 and it's there
