### ISSUE TITLE
Use go-acme official image?

### ISSUE THREAD

**Issue by sit** [kchristensen/udm-le#13]
Why does `udm-le.sh` use the hectormolinero image instead of https://hub.docker.com/r/goacme/lego/?

**Comment by kchristensen** [comment]
I believe it was because at the time I wrote this, they weren't publishing a docker image yet. I'll see about getting flipped over, thanks for pointing this out!

**Comment by kchristensen** [comment]
I recall now why I didn't use the official acme image initially -- they weren't building one for armv8 yet. Looks like they are now and it seems to work so I'll push out a new version soon.

**Comment by kchristensen** [comment]
Here you go! https://github.com/kchristensen/udm-le/releases/tag/1.0.5

**Comment by sit** [comment]
Works great, thanks!
