### ISSUE TITLE
On Dream Machine-udm-le.sh: line 91: podman: not found

### ISSUE THREAD

**Issue by dgirard96789** [kchristensen/udm-le#16]

**Comment by kchristensen** [comment]
What firmware version are you running?

**Comment by dgirard96789** [comment]
v1.5.6

**Comment by dgirard96789** [comment]
So it appears that perhaps I have very old firmware...silly me for believing the firmware update page on the UDM that says I'm running the latest available....

I'll try updating it tonight (after the kids are done with virtual school) and see what happens

**Comment by kchristensen** [comment]
Yup, once you're on UnifiOS it should work as expected.

**Comment by kchristensen** [comment]
How'd this end up? Good to go?
