### ISSUE TITLE
UCK-G2-Plus Compatibility

### ISSUE THREAD

**Issue by 88fingerslukee** [kchristensen/udm-le#19]
so the Cloud Key Gen2 Plus just got Unifi OS and I'm running the 2.0.22 FW. 

I'm trying to get this to work but the first issue is that /etc/init.d/crond is not found. It's called cron instead.  Second, podman is not installed and I can't seem to get it from aptitude. 

Any thoughts? Am I wrong in thinking this should work for the Cloud Key Gen2 plus?

thanks for all your help!

**Comment by 88fingerslukee** [comment]
I might add that I'm more than willing to help get this working on this device. Any info you need from me, just let me know.

**Comment by timrettop** [comment]
This whole solution is based on UDM and UMD Pro which support running docker containers using Podman.  It doesn’t seem that UI included podman with the Cloud Key, I’m guessing as its probably a much slower CPU.

-Tim Potter

**Comment by 88fingerslukee** [comment]
well poop.  That kinda bursts my bubble.

**Comment by kchristensen** [comment]
Yeah, this whole thing is predicated upon having podman/docker installed for easy running of acme. That's not to say that it's not possible to pull in an acme binary use that but it's considerably more messy.

**Comment by kchristensen** [comment]
I'm going to close this out -- if someone can figure out a clean way to do this in a non docker way that doesn't bloat everything up I'd consider merging it.
