### ISSUE TITLE
Feature Request - add support for the RADIUS certificate

### ISSUE THREAD

**Issue by emlynmac** [kchristensen/udm-le#21]
Hi - awesome work on this; made my day to be able to find the utilities and your lets encrypt support.

I see the script supports both the main cert and the portal - is it also possible to support the RADIUS server too?

I can dig in and make a PR if I have some direction as to how this works...

Thanks!

Emlyn

**Comment by kchristensen** [comment]
I should probably update the docs, but it does support the captive portal if you set ENABLE_CAPTIVE in your configuration. :)

**Comment by kchristensen** [comment]
Oh oops you said radius, not captive portal. Yeah a PR for that would be a welcome addition if you can swing it!

**Comment by emlynmac** [comment]
Ok, I found this: https://community.ui.com/questions/How-to-replace-RADIUS-certs-on-UDM-Pro/efa40805-de2f-48ba-a333-109ac7a49404

I'm not entirely sure this will work with just a cert; may need a CA anyway. Need to brush up on how this all works...

**Comment by emlynmac** [comment]
So my understanding is that you need a CA that you trust for doing RADIUS and that this should not be a publicly trusted CA. Given this, it doesn't make sense to use LE for this. Closing.
