### ISSUE TITLE
DNS Provider

### ISSUE THREAD

**Issue by eridannus** [kchristensen/udm-le#22]
Hi!

I hope someone can help me. I just bought a domain in Google Domains, and I'm trying to set up a certificate for my UDMP. The thing is I don't know how to configure the DNS provider option. I don't even know if this is possible or maybe I need something else...

Thanks in advance for your help!

**Comment by murphm8** [comment]
Assuming you want to use Cloudflare since it is compatible with this script you will need to point your domain at the Cloudflare nameservers. Check out https://support.cloudflare.com/hc/en-us/articles/205195708-Changing-your-domain-nameservers-to-Cloudflare.

**Comment by kchristensen** [comment]
Additionally, I just merged support for GCP Cloud DNS (Google) and we also have support for AWS Route 53 as well if you don't want to use Cloudflare. The README.md should outline what you need to do to set any of those up.
