### ISSUE TITLE
trying to use http-01

### ISSUE THREAD

**Issue by FreezyExp** [kchristensen/udm-le#26]
Here is what I have tried so far:

adding to LEG_ARGS in udm-le.sh:
--http --http.port :81 

and while testing:
--server https://acme-staging-v02.api.letsencrypt.org/directory

Adding port forwarding from 80 to 81

`acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://<url>/.well-known/adme-challenge/<token>: Timeout during connect (likely firewall problem)
` 

Not sure if this method will even work as port 80 seems to be in use, most likely it's hidden and in use for unifi-os.

Anyone else got any ideas of things to try to get http-01 to work?

**Comment by kchristensen** [comment]
Eh, you're going to run into all sorts of problems trying this probably, since you're going to have to figure out how to modify firewall rules on the UDMP in order to open up whatever port you try to use. I'd really suggest getting DNS setup somewhere you can use DNS-01 challenges with.

**Comment by FreezyExp** [comment]
Yup I ended up just forwarding the ports to a server, then having that handle all the certificates.
As pushing certificates to the UDM pro is not that difficult.

So I abandoned this problem. shall I close the issue?

**Comment by kchristensen** [comment]
Yup, closing!
