### ISSUE TITLE
/etc/init.d/crond: not found on UDMP 1.8.6

### ISSUE THREAD

**Issue by Servery** [kchristensen/udm-le#27]
After UDMP firmware upgrade from 1.8.5 to 1.8.6 I tired to install the udm-le.sh script again, but it does not work anymore...

1. `unifi-os shell`
2. `mkdir /mnt/data`
3. `mkdir /mnt/data/udm-le`
4. `cd /mnt/data/udm-le`
4. `wget https://raw.githubusercontent.com/kchristensen/udm-le/master/udm-le.sh`
5. `chmod +x udm-le.sh`
6. `wget https://raw.githubusercontent.com/kchristensen/udm-le/master/udm-le.env`
7. `apt install nano`
8. `nano udm-le.env` set CERT_EMAIL, CERT_HOSTS, ENABLE_CAPTIVE=yes, DNS_PROVIDER='cloudflare', CLOUDFLARE_DNS_API_TOKEN=my_cloudflare_API_token
9. `/mnt/data/udm-le/udm-le.sh initial`

concole output:
`root@ubnt:/mnt/data/udm-le# /mnt/data/udm-le/udm-le.sh initial`
`/mnt/data/udm-le/udm-le.sh: 66: /mnt/data/udm-le/udm-le.sh: /etc/init.d/crond: not found`

If I change `/etc/init.d/crond reload ${CRON_FILE}` to `/etc/init.d/cron reload ${CRON_FILE}` on line 66 in /mnt/data/udm-le/udm-le.sh there is another error: 
`root@ubnt:/mnt/data/udm-le# /mnt/data/udm-le/udm-le.sh initial`
`Attempting initial certificate generation`
`/mnt/data/udm-le/udm-le.sh: 80: /mnt/data/udm-le/udm-le.sh: podman: not found`

**Comment by Servery** [comment]
sry... I should not have used the command `unifi-os shell`!!! Everything works just fine...

**Comment by deeps-1987** [comment]
> After UDMP firmware upgrade from 1.8.5 to 1.8.6 I tired to install the udm-le.sh script again, but it does not work anymore...
> 
> 1. `unifi-os shell`
> 2. `mkdir /mnt/data`
> 3. `mkdir /mnt/data/udm-le`
> 4. `cd /mnt/data/udm-le`
> 5. `wget https://raw.githubusercontent.com/kchristensen/udm-le/master/udm-le.sh`
> 6. `chmod +x udm-le.sh`
> 7. `wget https://raw.githubusercontent.com/kchristensen/udm-le/master/udm-le.env`
> 8. `apt install nano`
> 9. `nano udm-le.env` set CERT_EMAIL, CERT_HOSTS, ENABLE_CAPTIVE=yes, DNS_PROVIDER='cloudflare', CLOUDFLARE_DNS_API_TOKEN=my_cloudflare_API_token
> 10. `/mnt/data/udm-le/udm-le.sh initial`
> 
> concole output:
> `root@ubnt:/mnt/data/udm-le# /mnt/data/udm-le/udm-le.sh initial`
> `/mnt/data/udm-le/udm-le.sh: 66: /mnt/data/udm-le/udm-le.sh: /etc/init.d/crond: not found`
> 
> If I change `/etc/init.d/crond reload ${CRON_FILE}` to `/etc/init.d/cron reload ${CRON_FILE}` on line 66 in /mnt/data/udm-le/udm-le.sh there is another error:
> `root@ubnt:/mnt/data/udm-le# /mnt/data/udm-le/udm-le.sh initial`
> `Attempting initial certificate generation`
> `/mnt/data/udm-le/udm-le.sh: 80: /mnt/data/udm-le/udm-le.sh: podman: not found`

Hi

I am new to this and followed along with your steps till 10 on my UDM-P and keep getting the error:

```
"root@ubnt:/# /mnt/data/udm-le/udm-le.sh initial
bash: /mnt/data/udm-le/udm-le.sh: No such file or directory"
```

I can only navigate to /mnt/ and when I "ls" only "persisted" shows but Winscp clearly shows more
![image](https://user-images.githubusercontent.com/86173500/122658559-b183b400-d166-11eb-93b4-d134480e4a27.png)
