### ISSUE TITLE
udm-le.sh initial failing with custom lego provider

### ISSUE THREAD

**Issue by cHaos91** [kchristensen/udm-le#34]
runnning:
 ./udm-le.sh initial 
in folder /mnt/data/udm-le
returns error:
/.udm-le.sh: /mnt/data/udm-le/udm-le.env: line 20: lego: not found

[udm-le.env.txt](https://github.com/kchristensen/udm-le/files/6479125/udm-le.env.txt)

**Comment by kchristensen** [comment]
The issue you're seeing is because on line 20 of your environment file you're trying to call lego to issue a cert using DuckDNS as your provider, which is not technically supported in udm-le. 

This isn't to say that it couldn't be,but what you're attempting isn't how you'd go about implementing it.

**Comment by cHaos91** [comment]
any hints on how to correctly implement this or a way to get this provider supported?

**Comment by kchristensen** [comment]
I'm not near a computer at the moment but changing the DNS_PROVIDER variable to duckdns and specifying the token in the env file may be all you need to do.

**Comment by cHaos91** [comment]
thank you I will give that a try

**Comment by kwschnei** [comment]
When I set min up to work with Linode, I had to do the following. Maybe this will help.

```
DNS_PROVIDER='linode'
LEGO_EXPERIMENTAL_CNAME_SUPPORT=TRUE
LINODE_TOKEN=###############
LINODE_PROPAGATION_TIMEOUT=120
```

**Comment by cHaos91** [comment]
turns out this is all i needed,
perhapse we can add it to the tested and supported providers.


#DuckDNS Provider
DNS_PROVIDER='duckdns'
DUCKDNS_TOKEN=xxxxxx-xxxxx-xxxx-xxxx-xxxxxxxx
