### ISSUE TITLE
Assignees

### ISSUE THREAD

**Issue by tunlin8888** [kchristensen/udm-le#36]
server.log:[2021-03-15T00:51:08,542] <inform-13> ERROR system - Unable to read certificate from the unifi chain. There are 2 certificates, but exactly 1 is expected

server.log:[2021-03-15T00:51:09,241] <inform-13> ERROR dev - WiFiman enabled but could not find certificate, skipping config

**Comment by kchristensen** [comment]
What you're seeing is covered here: https://github.com/kchristensen/udm-le/issues/30

**Comment by kwschnei** [comment]
Covered, but not resolved.
