### ISSUE TITLE
Certificate Generated Not Deployed

### ISSUE THREAD

**Issue by pcburcham** [kchristensen/udm-le#41]
Running initial, I get through the certificate generation without a hitch - using Cloudflare for DNS and I see in their logfile where the challenge records are written and deleted successfully. At the end of the process, the certificate is not installed and stalls with message: "New certificate was generated, time to deploy it".

 I've deleted/replaced files, rebooted router, restarted shell, but no luck with it yet. No errors, just sits at the message above. Nothing interesting in the UDM logs either. Ideas?

UDM Pro (v1.11.0-14)

**Comment by kchristensen** [comment]
Ah interesting, I see the same thing happening on mine now that I am on v1.110-14. It seems to be hanging when issuing the `unifi-os restart`. 

I'll have to poke at it a bit to see if I can't figure out what it's upset about. In the mean time if you ctrl-c out of it and just run a `unifi-os restart` it should restart successfully and deploy your certificate.

**Comment by kchristensen** [comment]
Do me a favor, try editing `udm-le.sh` and remove the trailing ` &` on lines 82, 88 and 93 and see if that fixes it for you?

**Comment by pcburcham** [comment]
That seems to have worked and allowed the script to complete. As Elvis Presley would have said, "Thank you...Thank you very much!"

**Comment by pcburcham** [comment]
Sidebar: For those experiencing issues with hostnames and unable to access via domain name on current network application 6.4.49, beta 6.4.52 fixes this. It's also worth noting that you may have to toggle between Official and Early release channels and refresh the browser a few times to get the update to complete - at least on a UDMP. This has been reported in the Ubiquiti forums. 

I'm going to reopen and post to make this more visible @kchristensen. Close it if you don't feel like it's necessary. And thanks again for your help.
