### ISSUE TITLE
[FEATURE] Generate any number of certificates

### ISSUE THREAD

**Issue by Ulrar** [kchristensen/udm-le#43]
Hi,

I've just moved my haproxy instance directly on my UDM Pro, using udm-utilities.
For now I've copy pasted my certificates directory manually, but I wonder if there's a way to use this udm-le to handle renewing them automatically ?

Basically in addition to generating and installing a certificate for the UDM, it would also need to generate some .pem files in a given directory, and ideally run `prodman restart haproxy` afterwards.

Thanks

**Comment by kchristensen** [comment]
I'm going to close this out -- I don't feel that it really falls within the scope of what I think udm-le is for. If you'd like more certificates for use elsewhere on your network, just use lego to generate as many as you want elsewhere as there's effectively no limit to how many you can make.
