### ISSUE TITLE
[FEATURE] Update Guest Portal Certificate Keystore - updated code below works

### ISSUE THREAD

**Issue by Rosco1014** [kchristensen/udm-le#45]
This process works great for updating the SSL cert served when accessing the UDM pro admin interface, however, it does not update the Guest Portal. This cert is stored as a keystore and you need to run two additional commands to first create the pkcs12 and then use that to import via keytool.

> cp podman exec unifi-os openssl pkcs12 -export -in ${UBIOS_CERT_PATH}/unifi-core.crt -inkey ${UBIOS_CERT_PATH}/unifi-core.key \-out ${UBIOS_CERT_PATH}/unifi.p12 -name unifi -caname root -passin pass:aircontrolenterprise -passout pass:aircontrolenterprise
cp podman exec unifi-os keytool -noprompt -importkeystore -srckeystore ${UBIOS_CERT_PATH}/unifi.p12 -srcstoretype PKCS12 -srcstorepass aircontrolenterprise -destkeystore /usr/lib/unifi/data/keystore -storepass aircontrolenterprise

The new deploy_cert() function looks like:
>deploy_cert() {
	# Re-write CERT_NAME if it is a wildcard cert. Replace * with _
	LEGO_CERT_NAME=${CERT_NAME/\*/_}
	if [ "$(find -L "${UDM_LE_PATH}"/lego -type f -name "${LEGO_CERT_NAME}".crt -mmin -5)" ]; then
		echo 'New certificate was generated, time to deploy it'
		# Controller certificate
		cp -f ${UDM_LE_PATH}/lego/certificates/${LEGO_CERT_NAME}.crt ${UBIOS_CERT_PATH}/unifi-core.crt
		cp -f ${UDM_LE_PATH}/lego/certificates/${LEGO_CERT_NAME}.key ${UBIOS_CERT_PATH}/unifi-core.key
		chmod 644 ${UBIOS_CERT_PATH}/unifi-core.*
		cp podman exec unifi-os openssl pkcs12 -export -in ${UBIOS_CERT_PATH}/unifi-core.crt -inkey ${UBIOS_CERT_PATH}/unifi-core.key \-out ${UBIOS_CERT_PATH}/unifi.p12 -name unifi -caname root -passin pass:aircontrolenterprise -passout pass:aircontrolenterprise
		cp podman exec unifi-os keytool -noprompt -importkeystore -srckeystore ${UBIOS_CERT_PATH}/unifi.p12 -srcstoretype PKCS12 -srcstorepass aircontrolenterprise -destkeystore /usr/lib/unifi/data/keystore -storepass aircontrolenterprise
		NEW_CERT="yes"
	else
		echo 'No new certificate was found, exiting without restart'
	fi
}

**Comment by kchristensen** [comment]
Seems like a great addition, how would you feel about opening a PR with these changes?

**Comment by Rosco1014** [comment]
Even if you're not using it, you can still preview the captive portal login page by visiting this URL: https://udm-pro-URL:8843/guest/s/default/#/

It's not documented well at all on the Unifi side, but the actual captive portal SSL cert is updated/housed in a keystore. I believe there's a redirector for the portal, as well as the portal's captive portal login page.

Maybe you can make more sense of this than me, there's actually 3 SSL cert locations to cover the entire device.

UDM Pro SSL Cert locations:

UDM Pro:
/mnt/data/unifi-os/unifi-core/config/unifi-core.crt
/mnt/data/unifi-os/unifi-core/config/unifi-core.key

Guest Network/Redirectors:
/mnt/data/system/ssl/private/redirector/server.crt
/mnt/data/system/ssl/private/redirector/server.key

Keystore: (captive portal login page https://udm-pro-URL:8843/guest/s/default/#/ )

**Comment by Rosco1014** [comment]
I was trying to validate this a bit more but the LE SSL cert service is ironically down lol... I'll report back later, thanks for sticking with this and all your time for this project!

**Comment by kchristensen** [comment]
Closing this out -- the latest release does have captive portal support. Please test that out and open a new issue if there are issues.

**Comment by KarlBaumann** [comment]
This still does not seem to work or maybe I am doing something wrong.
I did set the ENABLE_CAPTIVE to "yes"
Then I did run the `udm-le.sh initial`
And afterwards also `udm-le.sh update_keystore`

And the certificate on the "https://domain.com:8843/guest/s/default/#/" is still not changed.

**Comment by KarlBaumann** [comment]
Update: it looks like the a reboot was necessary.

**Comment by kchristensen** [comment]
I imagine there’s some service that needs to get bounced in order for it to take effect, what that is however I am unsure.

**Comment by joshrivers** [comment]
@KarlBaumann @kchristensen I was in the same boat, where the cert did not change. `systemctl restart unifi` caused it to reload correctly. (I'm not sure if there's a better way than bouncing the whole Network service)

**Comment by ermanno00** [comment]
> @KarlBaumann @kchristensen I was in the same boat, where the cert did not change. `systemctl restart unifi` caused it to reload correctly. (I'm not sure if there's a better way than bouncing the whole Network service)

Have you solved?
