### ISSUE TITLE
[BUG?] Failed to pull Lego

### ISSUE THREAD

**Issue by Sphyix** [kchristensen/udm-le#48]
**Describe the bug**
Cannot pull Lego

```
# /mnt/data/udm-le/udm-le.sh initial
Attempting initial certificate generation
Trying to pull docker.io/goacme/lego:v4.4.0-arm.v8...
  Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:51576->127.0.0.1:53: i/o timeout
Error: unable to pull docker.io/goacme/lego:v4.4.0-arm.v8: unable to pull image: Error initializing source docker://goacme/lego:v4.4.0-arm.v8: pinging docker registry returned: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:51576->127.0.0.1:53: i/o timeout
```
I tried setting custom DNS in the .env file aswell, no change.
Not sure where the issue is

**To Reproduce**
1- Copy files to UDM pro
2- edit variables, I used duckdns
3- for some reasons udm-le.sh wasn't set to be executable, set it with `chmod +x udm-le.sh`
4- run `/mnt/data/udm-le/udm-le.sh initial`

**Expected behavior**
Expected to work.

**Version Information (please complete the following information):**
 - UniFi OS: [1.11.0-16]
 - Hardware Type:  UDM-Pro

**Comment by kchristensen** [comment]
Looks to me like docker (podman) on your UDMP is not running somehow? What does this return:

```
❯ podman pull goacme/lego:v4.4.0-arm.v8                                                                                                                               ✘ 1
v4.4.0-arm.v8: Pulling from goacme/lego
595b0fe564bb: Pull complete
b9777d26d1b8: Pull complete
a57f83eb81af: Pull complete
7a6ed3024318: Pull complete
Digest: sha256:9b1ffd66b76ec7fa40041b576d144b456b58aa60f123cb61e348285810f8aee6
Status: Downloaded newer image for goacme/lego:v4.4.0-arm.v8
docker.io/goacme/lego:v4.4.0-arm.v8
```

I'm in the midst of moving and am currently not using my udmp so my ability to troubleshoot is going to be limited.

**Comment by Sphyix** [comment]
I found the culprit
![chrome_dqBssCy5E9](https://user-images.githubusercontent.com/17811922/140324519-a4d74e51-5cd8-4b6f-8676-b2b941a34234.png)
Even with a connection udm pro decided it didn't have an internet connection.
I mean, I posted this while I "didn't have internet connection"
Rebooted and it fixed itself

**Comment by kchristensen** [comment]
Glad you figured it out!
