### ISSUE TITLE
Issue initializing

### ISSUE THREAD

**Issue by oniroshi** [kchristensen/udm-le#50]
upon running the script i get :

Attempting initial certificate generation
No help topic for '<obfuscated>@gmail.com'

**Comment by kchristensen** [comment]
This is almost certainly because you have a typo in your .env file, go back and take a look and make sure everything is quoted properly, etc.

**Comment by oniroshi** [comment]
Here is my .env file:


#
# Required configuration
#

# Email for LetsEncrypt certificate issuance
CERT_EMAIL='changed@gmail.com'

# The FQDN of your UDMP (comma separated fqdns are supported)
CERT_HOSTS='unifi.changed.ddns.net'

# Enable updating Captive Portal support
ENABLE_CAPTIVE='yes'

# Enable updating Radius support
ENABLE_RADIUS='yes'

#
# DNS provider configuration
# See README.md file for more details
#

# AWS Route53
#DNS_PROVIDER='route53'

# Azure
#DNS_PROVIDER='azure'
#AZURE_CLIENT_ID=
#AZURE_CLIENT_SECRET_FILE=/root/.secrets/client-secret.txt
#AZURE_ENVIRONMENT=public
#AZURE_RESOURCE_GROUP=udm-le
#AZURE_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
#AZURE_TENANT_ID=

# CloudFlare
# Note: Quoting your CLOUDFLARE_DNS_API_TOKEN below seems to cause issues
#DNS_PROVIDER='cloudflare'
#CLOUDFLARE_DNS_API_TOKEN=YOUR_CLOUDFLARE_API_TOKEN

# Digital Ocean
# Note: Quoting your DO_AUTH_TOKEN below seems to cause issues
#DNS_PROVIDER='digitalocean'
#DO_AUTH_TOKEN=AUTH_TOKEN

# DuckDNS
#DNS_PROVIDER='duckdns'
#DUCKDNS_TOKEN=AUTH_TOKEN

# Google Cloud DNS
# Note: The default path for the service account file is /root/.secrets
#DNS_PROVIDER='gcloud'
#GCE_SERVICE_ACCOUNT_FILE=/root/.secrets/sa.json
#GCE_PROPAGATION_TIMEOUT=3600

#
# Change stuff below at your own risk
#

# Container Image configuration
CONTAINER_IMAGE='docker.io/goacme/lego'
CONTAINER_IMAGE_TAG='v4.4.0-arm.v8'

# DNS_RESOLVERS supports a host:port if you need to override system DNS
DNS_RESOLVERS=''

# Changing below requires changing line 6 of udm-le.sh
UDM_LE_PATH='/mnt/data/udm-le'

# These should only change if Unifi-OS core changes require it
CERT_IMPORT_CMD='java -jar /usr/lib/unifi/lib/ace.jar import_key_cert'
UBIOS_CONTROLLER_CERT_PATH='/mnt/data/unifi-os/unifi-core/config'
UBIOS_RADIUS_CERT_PATH='/mnt/data/udapi-config/raddb/certs'
UNIFIOS_CERT_PATH='/data/unifi-core/config'

**Comment by oniroshi** [comment]
im behind a reverse proxy and use dynamic dns

**Comment by oniroshi** [comment]
i switched to the HTTPREQ dns provider and now i get :


# /mnt/data/udm-le/udm-le.sh initial
Attempting initial certificate generation
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] acme: Obtaining bundled SAN certificate
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/62260177590
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] acme: Could not find solver for: tls-alpn-01
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] acme: Could not find solver for: http-01
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] acme: use dns-01 solver
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] acme: Preparing to solve DNS-01
2021/12/26 20:25:20 [INFO] [unifi.changed.ddns.net] acme: Cleaning DNS-01 challenge
2021/12/26 20:25:20 [WARN] [unifi.changed.ddns.net] acme: cleaning up failed: httpreq: Post "/'unifi.changed.ddns.net'/cleanup": unsupported protocol scheme ""
2021/12/26 20:25:20 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/62260177590
2021/12/26 20:25:20 Could not obtain certificates:
        error: one or more domains had a problem:
[unifi.changed.ddns.net] [unifi.changed.ddns.net] acme: error presenting token: httpreq: Post "/'unifi.changed.ddns.net'/present": unsupported protocol scheme ""

**Comment by kchristensen** [comment]
HTTP challenge is never going to work, mostly because the firewall would need to be opened up to allow the inbound http requests.

I can't really tell if there's any issues with your env file due to the formatting, what DNS provider were you trying to use?

**Comment by mtalexan** [comment]
@oniroshi Your quoting on the env file you pasted is all screwed up. Create a mulit-line code block by putting 3 backticks on a separate line before and after the literal code, and paste in your env file. Look at it in Preview before you submit.
```
It should
Look like
This
```

**Comment by oniroshi** [comment]
I use dynamic dns from no-ip so I cant really use any other dns provider

**Comment by kchristensen** [comment]
How were you trying to configure no-ip in your .env file? I didn't see that in the config you posted above, only http related stuff which as mentioned is not going to work.
