### ISSUE TITLE
Cant run last command to initial

### ISSUE THREAD

**Issue by campmeharder** [kchristensen/udm-le#52]
![Screenshot (18)](https://user-images.githubusercontent.com/97767454/149596514-9f1cc97b-43d5-45b9-b4d5-669fc23da7bd.png)
Keep getting permissions denied. Cant seem to find why. Tried with sudo, sudo -o. This is my first time doing this, thanks for help

**Comment by kchristensen** [comment]
You're better off sshing in there and doing it, but this is because your script does not have execute permissions.

Try adding `sh ` before what you have in there.
