### ISSUE TITLE
on boot script

### ISSUE THREAD

**Issue by RikP** [kchristensen/udm-le#57]
For boostchicken's on-boot-script it is not clear for me what file to put in the `/mnt/data/on_boot.d`.

Is that the `/mnt/data/udm-le/udm-le.sh` but how to pass initial parameter then?
Or should i just copy `/mnt/data/on_boot.d/99-udm-le.sh` in there?

**Comment by kchristensen** [comment]
You copy the helper script `/mnt/data/on_boot.d/99-udm-le.sh` in there, not the actual meat and potatoes.

**Comment by RikP** [comment]
thanks!
