### ISSUE TITLE
Support Specifying Name Servers

### ISSUE THREAD

**Issue by owine** [kchristensen/udm-le#6]
I use a split horizon DNS with some local overrides for my desired domains. My UDMP is hitting these overrides when confirming propagation and does not continue. Lego supports specifying name servers and it would be great if the script allowed name servers to be specified in the .env file. Thanks

**Comment by kchristensen** [comment]
Seems reasonable, I'll see if I can't hack something together.

**Comment by kchristensen** [comment]
I just put out a release that adds support for specifying your own DNS resolvers, give it a shot: https://github.com/kchristensen/udm-le/releases/tag/1.0.3

**Comment by owine** [comment]
This appears to work as expected. Thanks! I am still having propagation issues but can see in logs the setting working.
