### ISSUE TITLE
[FEATURE]Update udm-le to support udm pro-se. 

### ISSUE THREAD

**Issue by olddude2** [kchristensen/udm-le#64]
**Is your feature request related to a problem? Please describe.**
Current udm-le will not run on udm pro-se since unifi-os shell and podman are no longer included. Response to udm-le.sh initial is:
/mnt/data/udm-le/udm-le.sh: 34: /mnt/data/udm-le/udm-le.sh: [[: not found
Attempting initial certificate generation
/mnt/data/udm-le/udm-le.sh: 176: /mnt/data/udm-le/udm-le.sh: podman: not found

**Describe the solution you'd like**
Provide  a clean updated fork solution for udm pro-se users seeking ssl certificate through a dns provider (e.g., cloudflare).

**Describe alternatives you've considered**
I've looked at various postings by others but have yet to find a solution that works. I also found a tread that you and team were trying to tackle this Nov 2021.

**Additional context**
I'm new at this but have been successful in using letsencrypt with traefik/portainer or certbot. However, I'm struggling with udm pro-se. If you have already developed a solution, please relay all the appropriate steps that need to be taken to get a ssl certificate (including a persistent solution or an add on to work even with a new firmware update). Thanks!

**Comment by kchristensen** [comment]
I imagine this is technically possible, but if it happens it's going to have to be a community contribution as I have no hardware to test this on. It is my understanding that eventually the UDMP will have 2.x firmware made available to it that no longer uses podman/docker, so at some point this project will die unless support for non-docker installs exists.

That said, I'm currently not using my udmp at all, so I'm relying on community support for most everything until I can get my hands on a UDW Pro, so we'd need someone willing to take on the work.

There's really 2 approaches, we create a `2.x` branch and start hacking in support for curling down the latest acme binary and using that, or hack in a test if `podman` is installed and if not branch the code path to do non-docker things.

**Comment by olddude2** [comment]
Thanks for the quick response.  I’m hoping that the community will take interest in a 2.x branch approach. However, I have yet to find a viable post on a 2.x branch to date. 

You’re doing great stuff. Cheers!

**Comment by scholdan** [comment]
Hello

Change #!/bin/sh to #!/bin/bash

and then there is some problems with the paths
Error: no container with name or ID "unifi-os" found: no such container

**Comment by lbouriez** [comment]
Any update on this ?

**Comment by scsa20** [comment]
I'm guessing it's more likely because Unifi ditched the container approached for a lot of things which means the unifi-os command no longer exists. The beta for version 2 of the UnifiOS is now out too that that people can test on. Hopefully within a few more months the UDM/UDM Pro will be on the same branch as UDM-SE to make it easier to manage.

**Comment by olddude2** [comment]
Check out the following link: https://scotthelme.co.uk/setting-up-https-on-the-udm-pro/

I successfully adapted his blog post to get SSL working on udm pro-se. In my case, I copied a Let's Encrypt cert from certbot that hooks into a Cloudflare DNS token. All I needed to do was copy the full chain pem and the private key. Once the files were copied onto the udm pro se, I then rebooted the server. Your situation might be different.

Steps:
1. SSH and copy the Let's Encrypt full chain pem  and paste the fullchain.pem (from another vm) into a new notepad ++ file
2. Copy the private key SSLCertificateKeyFile and paste into temp notepad ++
3. SSH into udm pro se and backup existing full chain pem and private key
mv unifi-core.crt unifi-core.crt_BAK
mv unifi-core.key unifi-core.key_BAK
4. Copy fullchain.pem and private key saved from steps 1 and 2 above into udm pro se. Note: Look at the headers and footers before overwriting because you may need to replicate them into the new fullchain.pem and private key.
nano unifi-core.crt
nano unifi-core.key
reboot

This solution unfortunately does not provide automatic renewal. Therefore, these steps will need to be repeated with the certificate requires renewal.

Note: I needed to sudo apt install nano. Alternative to nano is vim.

I'm sure there is a more elegant way but this got me over the hump until the communities comes up with a solution that enables renewal. I wasn't brave enough to install certbot onto the udm pro se.

**Comment by janknieling** [comment]
@kchristensen like mentioned in #67 Let’s Encrypt isn’t longer working on the normal UniFi dream machine pro because in UniFi OS 2.X docker support was dropped.
Docker has to be installed manually via the udm utilities from boostchicken

**Comment by kchristensen** [comment]
I haven't had time to dig into it yet as my UDMP isn't even racked up at the moment, but I don't think the right path forward is going to involve trying to cram Docker into a device that doesn't ship with it. I'd welcome a PR that just replaces Docker support with the installation of a Lego binary (from the Lego github releases page), but I don't have a solid timeframe for when I'm going to get around to hacking on it myself.

**Comment by kchristensen** [comment]
Hi all, we have had some generous users work on getting 2.x support finalized, please check out this PR and see how things are working for your use case: https://github.com/kchristensen/udm-le/pull/70

**Comment by kchristensen** [comment]
We've got a working branch for 2.x in the `development` branch located here, feel free to give this a shot before an official release: https://github.com/kchristensen/udm-le/tree/development

**Comment by JimSR** [comment]
Tested this on UDM-Pro running on 3.0.20. Works like a charm
