### ISSUE TITLE
Unifi-OS 2.4.23 breaks udm-le

### ISSUE THREAD

**Issue by MarkBurchard** [kchristensen/udm-le#67]
Main issue: the udm-le.sh script errors out after UDM/B upgrade to 2.4.x firmware*

Main changes to Unifi-OS:
• podman is gone
• replaced by java
• main unifi path is /data/unifi-core/config

 Let me know if you need logs etc.

* https://community.ui.com/releases/UniFi-OS-Dream-Machines-2-4-23/aebbba64-9e7e-4151-bcca-34ed08761f08?page=24

**Comment by kchristensen** [comment]
Some work started here on 2.x+ support: https://github.com/kchristensen/udm-le/pull/68 

If anyone feels like tackling the swap from podman to grabbing a lego binary, have at it.

**Comment by rjmalagon** [comment]
Lego 0.3.1-4+b3 is installable via apt in UBIOS 2x, I will try to use this Lego with your script (and will try to adapt it).

**Comment by rjmalagon** [comment]
uhm, no, very ancient Lego there, but I will try the download thing like the Tailscale script for UDM from https://github.com/SierraSoftworks/tailscale-udm

**Comment by kchristensen** [comment]
Hi all, we have had some generous users work on getting 2.x support finalized, please check out this PR and see how things are working for your use case: https://github.com/kchristensen/udm-le/pull/70

**Comment by kchristensen** [comment]
We've got a working branch for 2.x in the `development` branch located here, feel free to give this a shot before an official release: https://github.com/kchristensen/udm-le/tree/development

**Comment by kchristensen** [comment]
2.x support has been officially released in: https://github.com/kchristensen/udm-le/releases/tag/2.0.1
