### ISSUE TITLE
[BUG] udm-le.sh initial encounters a systemd error on UDM Base

### ISSUE THREAD

**Issue by arjundhanjal** [kchristensen/udm-le#74]
**Describe the bug**
When trying to run `udm-le.sh initial` on UDM Base, I get the following error. 

```shell
root@UDM:/data/udm-le# ./udm-le.sh initial
install_lego(): Attempting lego installation
install_lego(): Downloading lego v4.10.2 from https://github.com/go-acme/lego/releases/download/v4.10.2/lego_v4.10.2_linux_arm64.tar.gz
install_lego(): Extracting lego binary from release and placing at /data/udm-le/lego
lego
install_lego(): Verifying integrity of lego binary
install_lego(): Verified lego v4.10.2:ce38abfaccc8c0558e7668c7cb12b3980a6c61e5
create_services(): Creating udm-le systemd service and timer
cp: cannot stat '/data/udm-le/resources/systemd/udm-le.service': No such file or directory
```

**To Reproduce**
1. Copy the latest udm-le files to `/data/udm-le`, configure `udm-le.env`, and run `chmod +x` on `udm-le.sh`
2. Run `udm-le.sh initial`
3. See error

**Expected behavior**
The script runs as expected, creating jobs and configuring my certificate

**Version Information (please complete the following information):**
 - UniFi OS: v2.5.16
 - Hardware Type:  UDMB

**Additional context**
* I am upgrading from the previous udm-le releases that supported UniFi OS 1.x.

**Comment by kchristensen** [comment]
Can you `ls -la /data/udm-le/resources/systemd/`? I'm guessing you didn't copy that directory up to your UDM when you copied the updated scripts.

**Comment by arjundhanjal** [comment]
Sigh. Silly mistake. Thanks.
