### ISSUE TITLE
Compatible with UniFi OS 3?

### ISSUE THREAD

**Issue by gitothy** [kchristensen/udm-le#77]
_Apologies for raising this as an issue or if it's already covered elsewhere._

Is udm-le compatible with the current release of UniFi OS 3.0.20? I'm pretty sure it would be as the [on-boot-script](https://github.com/unifi-utilities/unifios-utilities#on-boot-script-2x) is working with 3.x but just want to double check.

Many thanks to Kyle C for his efforts on this project.

**Comment by JimSR** [comment]
I'm using it successfully with no tweaks on 3.0.20

**Comment by kchristensen** [comment]
You won't need the on-boot-script with anything >= 2.x, we've replaced it with a simple systemd unit file which handles running the script at boot and sets up a timer for the renewal of the certificate. So, feel free to remove that if you're not using it for anything else.
