### ISSUE TITLE
[FEATURE] Officially support NVR Pro

### ISSUE THREAD

**Issue by DDxPlague** [kchristensen/udm-le#80]
**Is your feature request related to a problem? Please describe.**
Provide official support for Unifi NVR and NVR Pro

**Describe the solution you'd like**
I ran the script today and it works on my NVR Pro running UniFi OS 3.1.12. Opening this feature so we could update documentation or track full fledged support.

**Describe alternatives you've considered**
None, this tool works today

**Additional context**

**Comment by kchristensen** [comment]
Thanks for testing this out! I've updated the supported device list in the readme to reflect that it works on the UNVRs.
